### ISSUE TITLE
Broadcasted piping .|>

### ISSUE THREAD

**Issue by mcabbott** [c42f/Underscores.jl#20]
Seems like this ought to work:
```julia
julia> @_ 1:4 .|> float |> filter(iseven(Int(_)), __) .|> sqrt              
#27 (generic function with 1 method)

julia> 1:4 .|> float |> xs -> filter(x -> iseven(Int(x)), xs) .|> sqrt 
2-element Array{Float64,1}:
 1.4142135623730951
 2.0
```
See also https://discourse.julialang.org/t/in-pipe-pipe-followed-by-gives-an-error/47174 for other examples.

**Comment by mcabbott** [comment]
Fix also allows this, in which `__` now sometimes means an element, I think that's OK:
```julia
julia> @_ 2 |>  __ .+ (1:3)  .|>  __^2 |> filter(isodd(_), __)
2-element Array{Int64,1}:
  9
 25
```

**Comment by c42f** [comment]
> `__` now sometimes means an element

I guess this should work, odd as it is!
