### ISSUE TITLE
Release a new version to make new bugfixes avaiable

### ISSUE THREAD

**Issue by melonedo** [c42f/Underscores.jl#22]
Hello! I really enjoy using your package in my personal project, but one thing keeps bothering me i s that pipe operators are not handled, so I have to avoid it explicitly. This has already been fixed in #21 but is not included in a release. 
It has been one year since the last release (2.0.0), can you release a new version to make the new bugfixes available?

**Comment by c42f** [comment]
I hadn't released a new version because I wanted to get some other breaking changes done in addition to the ones which have already gone in (particularly #12).

But at this point I clearly haven't got around to it, so yeah, let's release a new version. It'll have to be 3.0.0.

**Comment by c42f** [comment]
See https://github.com/JuliaRegistries/General/pull/48189

**Comment by melonedo** [comment]
Oh that is really fast! Thank you!

**Comment by c42f** [comment]
You're welcome.

@mcabbott deserves the credit for the fixes in this release. Thanks Michael!
