### ISSUE TITLE
Switch to more local `@_`

### ISSUE THREAD

**Issue by MasonProtter** [c42f/Underscores.jl#26]
So I realized here: https://github.com/JuliaLang/julia/issues/38713#issuecomment-1437448975 that we actually **can** have `map(@_ 1 + _[1], v)` or whatever do the right thing. Maybe this should be the canonical usage of this macro instead of being outside the `map`.

**Comment by mcabbott** [comment]
Oh that's pretty magical, I didn't know we could return "naked" tuples. Splat at production not consumption. Mathematica has something like this, but I thought Julia didn't. 
```julia
julia> map(@_ _^2, [1 2 3])
1×3 Matrix{Int64}:
 1  4  9

julia> @macroexpand1(@_ _^2, [1 2 3])
:(((var"##x#301"->begin
              #= REPL[12]:12 =#
              var"##x#301" ^ 2
          end), [1 2 3])...)

julia> dump(ans)
Expr
  head: Symbol ...
  args: Array{Any}((1,))
    1: Expr
      head: Symbol tuple
```

**Comment by MasonProtter** [comment]
I feel quite silly because I've known we could do this for years, but never made the connection that it could be used to bypass https://github.com/JuliaLang/julia/issues/36547

**Comment by tpapp** [comment]
> Oh that's pretty magical, I didn't know we could return "naked" tuples.

Is this documented anywhere?

**Comment by MasonProtter** [comment]
Since this would be a major departure from how this package works, I think I'll close this in favour of just making a new package: https://github.com/MasonProtter/SimpleUnderscores.jl

**Comment by c42f** [comment]
Sounds good!
